# Introduction to Robot Intelligence HW 1: Coding Questions

The is the coding potion of Homework 1. These questions are aimed at testing your ability to code up fundamental mathematical operations using Python and the numpy library.

For submission instructions, please see the theory portion of Homework 1.

In [1]:
import numpy as np
import math

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


## Part 1 : Solve Systems of linear equations

Given n linear equations with at most `n` unknown variables, write a function `solve_system` that can solve an arbitrary system of equations. Your function should output a single vector of values that satisfies the system. You may assume that `n <= 4`.

The system of equations will be provided as a list of strings as seen in `test_eq`. You may also assume that the variables will always be denoted as `a`, `b`, `c`, and `d`.


In [2]:
def parse_equations(equations):

  variables = set()
  coefficients_list = []
  constants_list = []


  for equation_str in equations:

    coefficients = {}
    constant = None

    equation_str = equation_str.replace(' ', '')

    equation_parts = equation_str.split('=')
    left_side = equation_parts[0].strip()
    new_left_side = ''
    for e in left_side:
      if e == '-':
        new_left_side += '+-'
      else:
        new_left_side += e
    left_side = new_left_side
    left_side_terms = left_side.split('+')

    right_side = equation_parts[1].strip()

    for term in left_side_terms:
      term = term.strip()
      if term:
        variable = term[-1]
        variables.add(variable)

        if term[:-1] == '':
          coefficient = 1
        elif term[:-1] == '-':
          coefficient = -1
        else:
          coefficient = float(term[:-1])

        coefficients[variable] = coefficients.get(variable, 0.0) + coefficient

    constant = float(right_side)

    coefficients_list.append(coefficients)
    constants_list.append(constant)

  variables = list(variables)
  variables.sort()

  num_equations = len(equations)
  num_variables = len(variables)
  A = np.zeros((num_equations, num_variables))
  b = np.array(constants_list)

  for i in range(len(coefficients_list)):
    for j, variable in enumerate(variables):
      A[i, j] = coefficients_list[i].get(variable, 0.0)
  return A, b

def solve_system(equations):
  """"
  Takes in a list of strings for each equation.
  Returns a numpy array with a row for each equation value
  """
  # TODO: Start
  A, b = parse_equations(equations)
  try:
    x = np.linalg.solve(A, b)
    x = x[:, np.newaxis]
    return x
  except np.linalg.LinAlgError:
    # Handle cases where the system is singular (no unique solution)
    return None
  # TODO: End


In [3]:
def test_eq():
  sys_eq = ['2 a + b - 3 c + d = 9',
            '-5 a + 1 b - 4 c + d = -14',
            'a + 2 b - 10 c = -7',
            'a + 2 b = 13']
  results = solve_system(sys_eq)
  expected = np.array([[3],[5],[2],[4]])

  assert(np.all(abs(expected-results) < 1e-10 ))

In [4]:
test_eq()

## Part 2 : Split a dataset into test and train

In supervised learning, the dataset is usually split into a train set (on which the model is trained) and a test set (to evaluate the trained model). This part of the homework requires writing a function `split_into_train_and_test` that takes a dataset and the test-train split ration as input, and provides the data split as an output. The function takes a `random_state` variable as input, which when kept the same outputs precisely the same split for arbitrary runs of the function.

In [5]:
def split_into_train_and_test(x_all_LF, frac_test=0.5, random_state=None):
    ''' Divide provided array into train and test sets along first dimension
    User can provide random number generator object to ensure reproducibility.
    Args
    ----
    x_all_LF : 2D np.array, shape = (n_total_examples, n_features) (L, F)
        Each row is a feature vector
    frac_test : float, fraction between 0 and 1
        Indicates fraction of all L examples to allocate to the "test" set
        Returned test set will round UP if frac_test * L is not an integer.
        e.g. if L = 10 and frac_test = 0.31, then test set has N=4 examples
    random_state : np.random.RandomState instance or integer or None
        If int, will create RandomState instance with provided value as seed
        If None, defaults to current numpy random number generator np.random.
    Returns
    -------
    x_train_MF : 2D np.array, shape = (n_train_examples, n_features) (M, F)
        Each row is a feature vector
        Should be a separately allocated array, NOT a view of any input array
    x_test_NF : 2D np.array, shape = (n_test_examples, n_features) (N, F)
        Each row is a feature vector
        Should be a separately allocated array, NOT a view of any input array
    Post Condition
    --------------
    This function should be side-effect free. Provided input array x_all_LF
    should not change at all (not be shuffled, etc.)
    Examples
    --------
    >>> x_LF = np.eye(10)
    >>> xcopy_LF = x_LF.copy() # preserve what input was before the call
    >>> train_MF, test_NF = split_into_train_and_test(
    ...     x_LF, frac_test=0.201, random_state=np.random.RandomState(0))
    >>> train_MF.shape
    (7, 10)
    >>> test_NF.shape
    (3, 10)
    >>> print(train_MF)
    [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
     [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
     [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
    >>> print(test_NF)
    [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
     [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
    ## Verify that input array did not change due to function call
    >>> np.allclose(x_LF, xcopy_LF)
    True
    References
    ----------
    For more about RandomState, see:
    https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
    '''
    if random_state is None:
        random_state = np.random
    # TODO: Start
    num_samples = x_all_LF.shape[0]
    num_test = math.ceil(frac_test * num_samples)

    test_indices = random_state.choice(num_samples, num_test, replace=False)

    test_mask = np.zeros(num_samples, dtype=bool)
    test_mask[test_indices] = True
    train_mask = ~test_mask

    train_samples = x_all_LF[train_mask]
    test_samples = x_all_LF[test_mask]
    return train_samples, test_samples
    # TODO: End


In [6]:
x_LF = np.eye(10)
xcopy_LF = x_LF.copy()
train_MF, test_NF = split_into_train_and_test(x_LF, frac_test=0.201, random_state=np.random.RandomState(0))
print(train_MF.shape)
print(test_NF.shape)
print(train_MF)
print(test_NF)

(7, 10)
(3, 10)
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


### Part 3: Solving a Search Problem

In this problem, given a list of N intervals, we want to find the closest non-overlapping interval greater than each interval in the dataset. The function `closest_interval` takes in the list of intervals and return a list of indices corresponding to the index of the closest interval for each element in the list. If a particular interval does not have a closest non-overlapping interval in the given list, return `-1` corresponding to that element in the list.

In [7]:
def closest_interval(intervals):
    #TODO: Start
    results = np.array([-1 for _ in range(len(intervals))])
    for i in range(len(intervals)):
      upper = intervals[i][1]
      closest_index = -1
      closest_lower = float('inf')
      for j in range(len(intervals)):
        if intervals[j][0] > upper and intervals[j][0] < closest_lower:
          closest_index = j
          closest_lower = intervals[j][0]
      results[i] = closest_index
    return results
    # TODO: End

In [8]:
intervals = np.array([[1, 4],
                      [2, 5],
                      [8, 9],
                      [6, 8],
                      [9, 10],
                      [3, 4],
                      [7, 9],
                      [5, 7]])

expected_closest_intervals = closest_interval(intervals)
print(expected_closest_intervals)

# Evaluate
results = np.array([7, 3, -1, 4, -1, 7, -1, 2])
assert(np.all(abs(expected_closest_intervals-results) < 1e-10 ))

[ 7  3 -1  4 -1  7 -1  2]
